CREATE TABLE dbo.MissingStations (
    station_id NVARCHAR(50) NOT NULL PRIMARY KEY,
    first_seen DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    last_seen  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    seen_count INT NOT NULL DEFAULT 1
);

